version: 2
updates:
  # Monitor main package.json for security alerts only (no PRs)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0