# Codecov configuration for Universal AI Encryption MCP
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "test/**/*"
  - "examples/**/*"
  - "dist/**/*"
  - "**/*.d.ts"
  - "**/*.config.*"
  - "**/index.ts"

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - src/
    carryforward: true

github_checks:
  annotations: true