packages:
  # Main package
  - "."
  # Examples intentionally excluded - they use file:../.. dependencies
  # and are installed separately to avoid pnpm workspace symlink issues
  # Tools
  - "tools/*"