source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "sass-embedded", "~> 1.69"
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem "just-the-docs", "~> 0.10.1"
  gem "jekyll-include-cache", "~> 0.2"
end
