name: Test Simple RPC AI Backend

permissions:
  contents: read

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    environment: test

    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests with coverage
        run: pnpm test:coverage -- --run --coverage --reporter=lcov,junit
        env:
          CI: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          if-no-files-found: warn
          compression-level: 6

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-report.junit.xml
          if-no-files-found: warn
          compression-level: 6

      - name: Upload coverage to Codecov
        if: matrix.node-version == 20 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: AWolf81/simple-rpc-ai-backend
          directory: coverage/
          files: 
            - ./coverage/lcov.info
            - ./coverage/integration-lcov.info
          flags: unittests, integration
          name: simple-rpc-ai-backend
          fail_ci_if_error: false
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test-report.junit.xml

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run integration tests with coverage
        run: pnpm test:integration -- --run --coverage --reporter=lcov,junit
        env:
          CI: true

      - name: Upload integration coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage
          path: coverage/
          if-no-files-found: warn
          compression-level: 6

      - name: Upload integration test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: test-report.junit.xml
          if-no-files-found: warn
          compression-level: 6
